#!/bin/bash

cp PlanetProfileV2018Comparison/inputPythonFiles/PPCallisto*.py Callisto/
cp PlanetProfileV2018Comparison/inputPythonFiles/PPEnceladus*.py Enceladus/
cp PlanetProfileV2018Comparison/inputPythonFiles/PPEuropa*.py Europa/
cp PlanetProfileV2018Comparison/inputPythonFiles/PPGanymede*.py Ganymede/
cp PlanetProfileV2018Comparison/inputPythonFiles/PPTitan*.py Titan/

./compareV2018.run

cp Callisto/*Profile*.txt PlanetProfileV2018Comparison/outputTextFiles/
cp Enceladus/*Profile*.txt PlanetProfileV2018Comparison/outputTextFiles/
cp Europa/*Profile*.txt PlanetProfileV2018Comparison/outputTextFiles/
cp Ganymede/*Profile*.txt PlanetProfileV2018Comparison/outputTextFiles/
cp Titan/*Profile*.txt PlanetProfileV2018Comparison/outputTextFiles/
rm PlanetProfileV2018Comparison/outputTextFiles/*Core.txt

cp Callisto/figures/*ComparisonHydrosphere* PlanetProfileV2018Comparison/
cp Enceladus/figures/*ComparisonHydrosphere* PlanetProfileV2018Comparison/
cp Europa/figures/*ComparisonHydrosphere* PlanetProfileV2018Comparison/
cp Ganymede/figures/*ComparisonHydrosphere* PlanetProfileV2018Comparison/
cp Titan/figures/*ComparisonHydrosphere* PlanetProfileV2018Comparison/
