#!/bin/bash

python PlanetProfileCLI.py Io/PPIo.py Europa/PPEuropa.py Ganymede/PPGanymede.py Callisto/PPCallisto.py Mimas/PPMimas.py Enceladus/PPEnceladus.py Dione/PPDione.py Rhea/PPRhea.py Titan/PPTitan.py Miranda/PPMiranda.py Ariel/PPAriel.py Umbriel/PPUmbriel.py Titania/PPTitania.py Oberon/PPOberon.py Triton/PPTriton.py Pluto/PPPluto.py

cp */*Profile*.txt PlanetProfileDefaultOutputs/outputTextFiles/
rm PlanetProfileDefaultOutputs/outputTextFiles/*Core.txt

cp PlanetProfile/Default/*/PP*.py PlanetProfileDefaultOutputs/inputPythonFiles/
rm PlanetProfileDefaultOutputs/inputPythonFiles/*InductOgram.py
