"""
Hybrid hydrosphere-thickness structure cache for PPTest45.

This module is intentionally isolated from the existing PPTest42 cache and MCMC
paths.  It runs PlanetProfile only to obtain a self-consistent hydrosphere PT
template for each Tb_K, then synthesizes whole-body structures by selecting a
total hydrosphere thickness and appending a constant-density, no-core silicate
interior.  The resulting total mass and C/MR^2 are outputs.
"""
import importlib
import logging
import pickle
import sys
import time
from itertools import product
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np

from PlanetProfile.Inference.structure_cache import save_structure_cache
from PlanetProfile.Utilities.Indexing import PhaseConv
from PlanetProfile.Utilities.defineStructs import Constants

log = logging.getLogger('PlanetProfile')

_MIN_LAYER_POINTS = 5


def build_hybrid_hydrosphere_grid(
    test_module_name: str,
    tb_values: Sequence[float],
    d_hydro_values_km: Sequence[float],
    cache_path: str,
    rho_sil_kgm3: Optional[float] = None,
    rheology: str = 'maxwell',
    convection_model: str = 'ds2001',
    force_rebuild: bool = False,
) -> Dict[str, Any]:
    """Build a hybrid grid over Tb_K x D_hydro_km.

    Args:
        convection_model: 'ds2001' (default) or 'yao2014' for Ice Ih convection.
    """
    cache_path = Path(cache_path)
    tb_grid = [float(v) for v in tb_values]
    d_grid = [float(v) for v in d_hydro_values_km]

    if cache_path.exists() and not force_rebuild:
        log.info(f"Loading hybrid hydrosphere grid from {cache_path}")
        with open(cache_path, 'rb') as f:
            cache_data = pickle.load(f)
    else:
        cache_data = {
            'grid_metadata': {
                'schema_version': 1,
                'cache_type': 'hybrid_hydrosphere_thickness',
                'source_module': test_module_name,
                'rheology': rheology,
                'convection_model': convection_model,
                'grid_parameters': ['Tb_K', 'D_hydro_km'],
                'grid_values': {'Tb_K': tb_grid, 'D_hydro_km': d_grid},
                'rho_sil_kgm3': rho_sil_kgm3,
                'assumptions': [
                    'Hydrosphere PT is generated by the self-consistent PlanetProfile hydrosphere calculation.',
                    'Total hydrosphere thickness is imposed after the hydrosphere template is generated.',
                    'The silicate interior is a constant-density no-core layer.',
                    'Mtot_kg and CMR2mean are computed outputs, not closure constraints.',
                ],
            },
            'grid_cache': {},
        }

    grid_cache = cache_data.setdefault('grid_cache', {})
    all_points = list(product(tb_grid, d_grid))
    missing = [point for point in all_points if _grid_key(point) not in grid_cache]

    if not missing:
        _log_hybrid_summary(grid_cache)
        return cache_data

    templates: Dict[float, Tuple[Any, Any]] = {}
    failed_tb: set = set()
    max_d_hydro_km = float(max(d_grid))
    t0 = time.time()
    for tb_k, d_hydro_km in missing:
        if tb_k in failed_tb:
            log.warning(f"Skipping D_hydro_km={d_hydro_km} — Tb_K={tb_k:.3f} template failed earlier")
            continue
        if tb_k not in templates:
            try:
                templates[tb_k] = _run_hydrosphere_template(
                    test_module_name,
                    tb_k,
                    rheology=rheology,
                    convection_model=convection_model,
                    max_d_hydro_km=max_d_hydro_km,
                )
            except Exception as exc:
                log.warning(f"Skipping Tb_K={tb_k:.3f}: template failed: {exc}")
                failed_tb.add(tb_k)
                continue
        Planet, Params = templates[tb_k]
        try:
            structure = synthesize_hybrid_structure(
                Planet,
                Params,
                d_hydro_km=d_hydro_km,
                rho_sil_kgm3=rho_sil_kgm3,
                rheology=rheology,
            )
        except Exception as exc:
            log.warning(f"Skipping Tb_K={tb_k:.3f}, D_hydro_km={d_hydro_km}: synthesis failed: {exc}")
            continue
        structure['grid_coordinates'] = {
            'Tb_K': float(tb_k),
            'D_hydro_km': float(d_hydro_km),
        }
        structure['source_module'] = test_module_name
        structure['rheology'] = rheology
        grid_cache[_grid_key((tb_k, d_hydro_km))] = structure
        _log_hybrid_row(structure)
        save_structure_cache(cache_data, cache_path)

    elapsed = time.time() - t0
    log.info(f"Hybrid hydrosphere grid complete: {len(grid_cache)}/{len(all_points)} "
             f"points in {elapsed/60:.1f} min")
    _log_hybrid_summary(grid_cache)
    cache_data['grid_metadata']['build_complete'] = True
    save_structure_cache(cache_data, cache_path)
    return cache_data


def synthesize_hybrid_structure(
    Planet,
    Params,
    d_hydro_km: float,
    rho_sil_kgm3: Optional[float] = None,
    rheology: str = 'maxwell',
) -> Dict[str, Any]:
    """Synthesize a whole-body TidalPy-ready structure from a PP hydrosphere."""
    radius_m = float(Planet.Bulk.R_m)
    d_hydro_m = float(d_hydro_km) * 1e3
    if d_hydro_m <= 0 or d_hydro_m >= radius_m:
        raise ValueError(f"D_hydro_km must be within (0, {radius_m/1e3:.1f}), got {d_hydro_km}")

    hydro_groups = _hydrosphere_groups(Planet, d_hydro_m)
    if not hydro_groups:
        raise ValueError(f"No hydrosphere layers found for D_hydro_km={d_hydro_km}")

    r_sil_top_m = radius_m - d_hydro_m
    rho_sil = float(rho_sil_kgm3 if rho_sil_kgm3 is not None
                    else getattr(Planet.Sil, 'rhoSilWithCore_kgm3', 3300.0))
    sil_group = _silicate_group(Planet, r_sil_top_m, rho_sil)

    groups_core_to_surface = [sil_group] + list(reversed(hydro_groups))
    structure = _groups_to_structure(Planet, groups_core_to_surface, rheology)

    mass, cmr2 = _mass_and_cmr2(groups_core_to_surface, Planet.Bulk.M_kg, radius_m)
    structure['Mtot_kg'] = mass
    structure['CMR2mean'] = cmr2
    structure['CMR2'] = cmr2
    structure['Mdiff_frac'] = abs(1.0 - mass / float(Planet.Bulk.M_kg))
    structure['D_hydro_km'] = float(d_hydro_km)
    structure['rhoSil_kgm3'] = rho_sil
    structure['rhoSilWithCore_kgm3'] = rho_sil
    structure['Tb_K'] = float(Planet.Bulk.Tb_K)
    structure['D_iceIh_km'] = _sum_group_thickness_km(hydro_groups, {1, Constants.phaseClath})
    structure['D_ocean_km'] = _sum_group_thickness_km(hydro_groups, {0})
    structure['D_hp_ice_km'] = _sum_group_thickness_km(hydro_groups, {2, 3, 5, 6})
    structure['D_iceIII_km'] = _sum_group_thickness_km(hydro_groups, {3})
    structure['D_iceV_km']   = _sum_group_thickness_km(hydro_groups, {5})
    structure['D_iceVI_km']  = _sum_group_thickness_km(hydro_groups, {6})
    structure['sigma_ocean_mean_Sm'] = _mean_ocean_sigma(Planet, d_hydro_m)
    structure['wOcean_ppt'] = float(getattr(Planet.Ocean, 'wOcean_ppt', np.nan))
    structure['R_body_m'] = radius_m
    return structure


def _run_hydrosphere_template(test_module_name: str, tb_k: float, rheology: str,
                              convection_model: str = 'ds2001',
                              max_d_hydro_km: float = 800.0):
    from PlanetProfile.GetConfig import Params as configParams
    from PlanetProfile.Main import PlanetProfile
    from PlanetProfile.Utilities.defineStructs import EOSlist

    EOSlist.loaded.clear()
    if test_module_name in sys.modules:
        importlib.reload(sys.modules[test_module_name])
    else:
        importlib.import_module(test_module_name)

    Planet = sys.modules[test_module_name].Planet
    Planet.Bulk.Tb_K = float(tb_k)
    if convection_model == 'yao2014':
        Planet.Do.SPHERICAL_CONVECTION = True
    else:
        Planet.Do.ARRHENIUS_VISCOSITY = False

    # Use CONSTANT_INNER_DENSITY so PP sets nHydro = nOceanMax (no MoI
    # truncation).  The grid builder only needs the hydrosphere PT template;
    # it synthesizes its own constant-density silicate layer at runtime.
    Planet.Do.CONSTANT_INNER_DENSITY = True
    Planet.Do.POROUS_ROCK = False
    Planet.Do.Fe_CORE = False

    # Extend hydrosphere to cover the full D_hydro grid range so the template
    # produces valid phases (including Ice VI) at all requested depths.
    Planet.Bulk.Dhsphere_m = max_d_hydro_km * 1e3 + 50e3

    configParams.Gravity.backend = 'tidalpy'
    if rheology == 'maxwell':
        configParams.Gravity.rheology_models = {
            '0': 'newton', 'Ih': 'maxwell', 'Ih_conv': 'maxwell',
            'II': 'maxwell', 'III': 'maxwell', 'III_conv': 'maxwell',
            'IV': 'maxwell', 'V': 'maxwell', 'V_conv': 'maxwell', 'VI': 'maxwell',
            'Sil': 'maxwell', 'Fe': 'elastic', 'Clath': 'elastic', 'Clath_conv': 'maxwell'
        }
    configParams.CALC_NEW = True
    configParams.CALC_NEW_GRAVITY = False
    configParams.NO_SAVEFILE = True
    configParams.SKIP_PLOTS = True
    configParams.CALC_CONDUCT = True
    configParams.ALLOW_BROKEN_MODELS = True

    # Keep PP from failing before the hydrosphere template is available.  The
    # hybrid path does not use PP's selected MoI-closed boundary.
    Planet.Bulk.CuncertaintyLower = 0.05
    Planet.Bulk.CuncertaintyUpper = 0.05

    log.info(f"Building hydrosphere PT template: {test_module_name}, Tb_K={tb_k:.3f}, "
             f"Dhsphere={Planet.Bulk.Dhsphere_m/1e3:.0f} km")
    Planet, Params = PlanetProfile(Planet, configParams)
    return Planet, Params


def _hydrosphere_groups(Planet, d_hydro_m: float) -> List[Dict[str, float]]:
    z_bounds = np.asarray(Planet.z_m, dtype=float)
    n_surf_ice = int(Planet.Steps.nSurfIce or 0)
    n_ocean_max = int(Planet.Steps.nOceanMax or 0)
    n_hydro_max = n_surf_ice + n_ocean_max
    if n_hydro_max == 0 or len(z_bounds) < 2:
        raise ValueError(
            f"Planet template for Tb_K={Planet.Bulk.Tb_K:.3f} has no hydrosphere layers "
            f"(nSurfIce={n_surf_ice}, nOceanMax={n_ocean_max}). "
            f"Check for PP convergence warnings."
        )
    max_template_depth = float(z_bounds[min(n_hydro_max, len(z_bounds) - 1)])
    if d_hydro_m > max_template_depth:
        raise ValueError(
            f"D_hydro_km={d_hydro_m/1e3:.3f} exceeds hydrosphere template depth "
            f"{max_template_depth/1e3:.3f} km for Tb_K={Planet.Bulk.Tb_K:.3f}"
        )

    raw_groups = []
    current = None
    for i in range(min(n_hydro_max, len(Planet.phase))):
        z_top = float(z_bounds[i])
        z_bot = float(z_bounds[i + 1])
        if z_top >= d_hydro_m:
            break
        z_bot = min(z_bot, d_hydro_m)
        if z_bot <= z_top:
            continue

        phase = _normalize_phase(int(Planet.phase[i]))
        conv = bool(i < len(getattr(Planet.Steps, 'iConv', [])) and Planet.Steps.iConv[i])
        props = _layer_props_from_planet(Planet, i, phase)
        interval = {
            'inner_m': float(Planet.Bulk.R_m - z_bot),
            'outer_m': float(Planet.Bulk.R_m - z_top),
            'phase': phase,
            'conv': conv,
            **props,
        }
        key = (phase, conv)
        if current is not None and current['key'] == key:
            current['intervals'].append(interval)
            current['inner_m'] = interval['inner_m']
        else:
            current = {
                'key': key,
                'phase': phase,
                'conv': conv,
                'outer_m': interval['outer_m'],
                'inner_m': interval['inner_m'],
                'intervals': [interval],
            }
            raw_groups.append(current)

    return [_collapse_group(group) for group in raw_groups]


def _layer_props_from_planet(Planet, i: int, phase: int) -> Dict[str, float]:
    rho = float(Planet.rho_kgm3[i])
    mu = float(Planet.Seismic.GS_GPa[i]) * 1e9
    vp = float(Planet.Seismic.VP_kms[i]) * 1e3
    eta = float(Planet.eta_Pas[i])
    k_pa = rho * vp**2 - 4.0 / 3.0 * mu
    if not np.isfinite(k_pa) or k_pa <= 0:
        k_pa = _fallback_bulk_modulus(phase, mu)
    return {
        'rho': rho,
        'mu_Pa': max(mu, 0.0),
        'K_Pa': max(k_pa, 1e6),
        'eta_Pa': eta if np.isfinite(eta) and eta > 0 else 1e19,
        'T_K': float(Planet.T_K[i]) if hasattr(Planet, 'T_K') else np.nan,
    }


def _silicate_group(Planet, r_outer_m: float, rho_sil: float) -> Dict[str, float]:
    mu_gpa = getattr(Planet.Sil, 'GSset_GPa', None)
    if mu_gpa is None or not np.isfinite(mu_gpa):
        mu_gpa = getattr(Planet.Sil, 'GSmean_GPa', np.nan)
    if not np.isfinite(mu_gpa):
        mu_gpa = Constants.GS_GPa[Constants.phaseSil]

    k_gpa = getattr(Planet.Sil, 'KSset_GPa', None)
    if k_gpa is None or not np.isfinite(k_gpa):
        k_gpa = getattr(Planet.Sil, 'KSmean_GPa', np.nan)
    if not np.isfinite(k_gpa):
        k_gpa = 120.0

    eta = getattr(Planet.Sil, 'etaRock_Pas', None)
    if isinstance(eta, (list, tuple, np.ndarray)):
        eta = eta[0]
    if eta is None or not np.isfinite(eta):
        eta = Constants.etaRock_Pas[0]

    return {
        'phase': Constants.phaseSil,
        'conv': False,
        'inner_m': 0.0,
        'outer_m': float(r_outer_m),
        'rho': float(rho_sil),
        'mu_Pa': float(mu_gpa) * 1e9,
        'K_Pa': float(k_gpa) * 1e9,
        'eta_Pa': float(eta),
        'T_K': np.nan,
    }


def _collapse_group(group: Dict[str, Any]) -> Dict[str, float]:
    intervals = group['intervals']
    volumes = np.array([
        4.0 / 3.0 * np.pi * (iv['outer_m']**3 - iv['inner_m']**3)
        for iv in intervals
    ])
    weights = volumes / np.sum(volumes)
    out = {
        'phase': int(group['phase']),
        'conv': bool(group['conv']),
        'inner_m': float(group['inner_m']),
        'outer_m': float(group['outer_m']),
    }
    for key in ('rho', 'mu_Pa', 'K_Pa', 'eta_Pa', 'T_K'):
        vals = np.array([iv[key] for iv in intervals], dtype=float)
        finite = np.isfinite(vals)
        if np.any(finite):
            out[key] = float(np.sum(vals[finite] * weights[finite]) / np.sum(weights[finite]))
        else:
            out[key] = np.nan
    return out


def _groups_to_structure(Planet, groups: List[Dict[str, float]], rheology: str) -> Dict[str, Any]:
    r_parts = []
    rho_parts = []
    k_parts = []
    mu_parts = []
    eta_parts = []
    phase_parts = []
    bulk_visc_parts = []
    temp_parts = []
    change_indices = [0]
    region_phases = []
    layer_upper_radii = []
    layer_types = []

    for idx, group in enumerate(groups):
        thickness = group['outer_m'] - group['inner_m']
        n_points = max(_MIN_LAYER_POINTS + 1, int(np.ceil(thickness / 25e3)) + 1)
        r_layer = np.linspace(group['inner_m'], group['outer_m'], n_points)
        if idx > 0 and r_parts and np.isclose(r_layer[0], r_parts[-1][-1]):
            r_layer = r_layer[1:]
        if len(r_layer) < _MIN_LAYER_POINTS:
            r_layer = np.linspace(group['inner_m'], group['outer_m'], _MIN_LAYER_POINTS)

        r_parts.append(r_layer)
        rho_parts.append(np.full(len(r_layer), group['rho']))
        k_parts.append(np.full(len(r_layer), group['K_Pa']))
        mu_parts.append(np.full(len(r_layer), group['mu_Pa']))
        eta_parts.append(np.full(len(r_layer), group['eta_Pa']))
        phase_parts.append(np.full(len(r_layer), group['phase']))
        bulk_visc_parts.append(np.zeros(len(r_layer)))
        temp_parts.append(np.full(len(r_layer), group.get('T_K', np.nan)))
        change_indices.append(change_indices[-1] + len(r_layer))

        phase_str = PhaseConv(int(group['phase']), liq='0')
        if group.get('conv', False):
            phase_str += '_conv'
        region_phases.append(phase_str)
        layer_upper_radii.append(float(group['outer_m']))
        layer_types.append('liquid' if int(group['phase']) == 0 else 'solid')

    r_m = np.ascontiguousarray(np.concatenate(r_parts), dtype=np.float64)
    rho = np.ascontiguousarray(np.concatenate(rho_parts), dtype=np.float64)
    k_pa = np.ascontiguousarray(np.concatenate(k_parts), dtype=np.float64)
    mu_pa = np.ascontiguousarray(np.concatenate(mu_parts), dtype=np.float64)
    eta_pa = np.ascontiguousarray(np.concatenate(eta_parts), dtype=np.float64)
    phases = np.ascontiguousarray(np.concatenate(phase_parts), dtype=np.float64)
    bulk_visc = np.ascontiguousarray(np.concatenate(bulk_visc_parts), dtype=np.float64)
    t_k = np.ascontiguousarray(np.concatenate(temp_parts), dtype=np.float64)

    omega = float(Planet.Bulk.meanMotion_radps)
    host_mass = Constants.parentMass_kg.get(Planet.parent, 1.898e27)
    return {
        'r_m': r_m,
        'rho': rho,
        'K_Pa': k_pa,
        'mu_Pa': mu_pa,
        'eta_Pa_base': eta_pa,
        'phases': phases,
        'bulk_visc': bulk_visc,
        'changeIndices': np.asarray(change_indices, dtype=int),
        'n_layers': len(groups),
        'layer_upper_radii': tuple(layer_upper_radii),
        'layer_types': tuple(layer_types),
        'region_phases': region_phases,
        'omega': omega,
        'eccentricity': float(Planet.Bulk.eccentricity),
        'host_mass': host_mass,
        'a_m': (Constants.G * host_mass / omega**2) ** (1.0 / 3.0),
        'phase_map': {0: '0', 1: 'Ih', 2: 'II', 3: 'III', 5: 'V', 6: 'VI'},
        'T_K': t_k,
        'bodyname': Planet.name,
        'rheology_type': rheology,
    }


def _mass_and_cmr2(groups: List[Dict[str, float]], observed_mass_kg: float, radius_m: float) -> Tuple[float, float]:
    mass = 0.0
    inertia = 0.0
    for group in groups:
        r_outer = group['outer_m']
        r_inner = group['inner_m']
        rho = group['rho']
        mass += 4.0 / 3.0 * np.pi * rho * (r_outer**3 - r_inner**3)
        inertia += 8.0 * np.pi / 15.0 * rho * (r_outer**5 - r_inner**5)
    return float(mass), float(inertia / (float(observed_mass_kg) * radius_m**2))


def _fallback_bulk_modulus(phase: int, mu_pa: float) -> float:
    if phase >= Constants.phaseSil:
        nu = 0.25
    elif phase == 0:
        return 2.2e9
    else:
        nu = 0.33
    return 2.0 * mu_pa * (1.0 + nu) / (3.0 * (1.0 - 2.0 * nu))


def _normalize_phase(phase: int) -> int:
    if Constants.phaseClath <= abs(phase) < Constants.phaseClath + 10:
        return Constants.phaseClath
    if phase >= Constants.phaseSil and phase < Constants.phaseSil + 10:
        return Constants.phaseSil
    return abs(phase)


def _sum_group_thickness_km(groups: List[Dict[str, float]], phases: set) -> float:
    return float(sum(
        (group['outer_m'] - group['inner_m']) / 1e3
        for group in groups
        if int(group['phase']) in phases
    ))


def _mean_ocean_sigma(Planet, d_hydro_m: float) -> float:
    sigma = getattr(Planet, 'sigma_Sm', None)
    if sigma is None:
        return np.nan
    vals = []
    for i in range(min(len(Planet.phase), len(sigma))):
        if Planet.z_m[i] >= d_hydro_m:
            break
        if int(Planet.phase[i]) == 0 and np.isfinite(sigma[i]):
            vals.append(float(sigma[i]))
    return float(np.mean(vals)) if vals else np.nan


def _grid_key(values: Sequence[float]) -> Tuple[float, ...]:
    return tuple(float(v) for v in values)


def _log_hybrid_row(structure: Dict[str, Any]) -> None:
    log.info(
        "HYBRID_GRID_POINT "
        f"Tb_K={structure['Tb_K']:.3f} "
        f"D_hydro_km={structure['D_hydro_km']:.3f} "
        f"Mtot_kg={structure['Mtot_kg']:.6e} "
        f"Mdiff_frac={structure['Mdiff_frac']:.6e} "
        f"CMR2mean={structure['CMR2mean']:.9f} "
        f"D_iceIh_km={structure['D_iceIh_km']:.3f} "
        f"D_ocean_km={structure['D_ocean_km']:.3f} "
        f"D_hp_ice_km={structure['D_hp_ice_km']:.3f}"
    )


def _log_hybrid_summary(grid_cache: Dict[Tuple[float, ...], Dict[str, Any]]) -> None:
    log.info("Hybrid hydrosphere grid summary:")
    for key in sorted(grid_cache):
        _log_hybrid_row(grid_cache[key])
