"""
SBI runner: single-round amortized Neural Posterior Estimation (NPE).

Implements the ``mode='sbi'`` branch of ``inference_core.run_inference``
(Phase B of plans/monte-carlo-sbi-implementation-plan.md). Trains a
normalizing-flow posterior estimator q(theta | x) on a prior-predictive
training set generated by ``MCMCRunner.generate_sbi_dataset``, then
conditions on the observed data to draw posterior samples.

Scientific conventions (do not change silently)
-----------------------------------------------
- **Theta space**: training and sampling happen in the *raw* parameter
  space of ``config.param_space``, in the order of its keys — identical
  to MCMC. Parameters named ``log10_*`` are ALREADY log10 quantities
  (e.g. log10 of viscosity in Pa·s); no additional log transform is
  applied here. ``Tb_K`` is in kelvin, ``alpha`` is dimensionless.
- **Prior**: ``BoxUniform`` built directly from ``config.param_space``
  bounds. This provably matches ``MCMCRunner._build_prior``'s
  ``scipy.stats.uniform(loc=low, scale=high-low)`` for
  ``prior_type='uniform'``. Non-uniform priors raise
  ``NotImplementedError`` (none of the current presets use them).
- **Imaginary-part convention**: training sets are generated with
  ``imag_convention='abs'`` — the x column for the Im(k2) observable
  stores |Im k2|, matching the MCMC likelihood and GUI convention.
  Conditioning values are likewise |Im k2|.
- **Flow density is NOT a likelihood**: the flow's log q(theta | x_obs)
  is a posterior-density estimate. It is stored in
  ``metadata['flow_log_prob']`` only. ``InferenceResult.log_likelihoods``
  holds the recomputed Gaussian chi^2 log-likelihood evaluated with the
  same ``MCMCRunner`` likelihood used for MCMC, so downstream consumers
  (e.g. ``get_best_fit``) see a true likelihood.
- **Weights**: SBI posterior draws are unweighted; ``weights=None``.

Lazy imports: this module imports without torch/sbi installed; an
informative ImportError is raised only when a method that needs them
runs. ``load_artifact`` does not require a structure cache.

Author: PlanetProfile Team
Date: 2026-07-04
"""
import json
import logging
import os
import subprocess
import time
import traceback
import warnings
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Dict, Optional, Tuple

import numpy as np

# Import-time stamp: lets long-running hosts (the Streamlit app) detect that
# this module's source changed on disk after import and prompt a restart —
# Streamlit hot-reloads page files but NOT imported library modules.
_MODULE_LOADED_AT = time.time()

log = logging.getLogger('PlanetProfile')

# Artifact schema version. Bump on any backwards-incompatible change to
# the dict layout written by save_artifact.
SBI_ARTIFACT_SCHEMA_VERSION = 1

# Directory where trained posterior artifacts live (see sbi_artifacts/INDEX.md).
SBI_ARTIFACTS_DIR = Path(__file__).parent / 'sbi_artifacts'

# Observable-name aliases for the imaginary part of k2. With
# imag_convention='abs' both names refer to the same |Im k2| column.
_IM_K2_ALIASES = ('Im_k2', 'abs_Im_k2')

# --- nflows neural-spline-flow sampling guard --------------------------------
# The nsf (neural spline flow) posterior estimator inverts a monotonic
# rational-quadratic spline when drawing samples. That inversion solves a
# quadratic whose discriminant (b^2 - 4ac) is analytically non-negative, but
# nflows guards it with a hard `assert (discriminant >= 0).all()`
# (nflows/transforms/splines/rational_quadratic.py). For a draw that lands
# essentially on a spline bin edge the *computed* discriminant can dip a hair
# below zero from pure floating-point roundoff (platform/BLAS dependent), which
# trips the assert and crashes the ENTIRE sample() call even though the rest of
# the batch is fine. The failure is intermittent — it depends on the random
# noise draw — so re-drawing with fresh RNG state almost always succeeds. See
# plans/HANDOFF-2026-07-09-test50-sbi-validation.md (Machine A 2026-07-16 note).
_SPLINE_ASSERT_MARKER = 'rational_quadratic'
# Max resample attempts before giving up. A persistent failure across this many
# independent noise draws is NOT roundoff — it signals the conditioning x sits
# in a genuinely pathological region of the flow, which must surface, not hide.
_MAX_SPLINE_RESAMPLE = 8
# Odd stride added to the base seed per retry so each attempt draws genuinely
# independent noise (a bare +1 would still walk nearby RNG states).
_SPLINE_RESEED_STRIDE = 1_000_003


def _is_nflows_spline_assertion(exc: BaseException) -> bool:
    """True if exc is the nflows rational-quadratic-spline discriminant assert.

    We match on the traceback frame filename rather than the (empty) message,
    since `assert (discriminant >= 0).all()` carries no text. Any other
    AssertionError must propagate unchanged — this guard is scoped to the one
    known floating-point-roundoff spline failure, not assertions in general.
    """
    if not isinstance(exc, AssertionError):
        return False
    for frame in traceback.extract_tb(exc.__traceback__):
        if _SPLINE_ASSERT_MARKER in (frame.filename or ''):
            return True
    return False


def _import_torch_sbi():
    """Import torch and sbi lazily with an informative error message."""
    try:
        import torch
        import sbi
    except ImportError as e:
        raise ImportError(
            "SBI mode requires the 'sbi' and 'torch' libraries. "
            "Install with: pip install 'sbi>=0.23,<0.27' torch\n"
            f"Original error: {e}"
        ) from e
    return torch, sbi


# Cache for the lazily-built truncated-normal Distribution subclass. torch is a
# lazy import in this module (it must import without torch installed), so the
# class — which must subclass torch.distributions.Distribution — cannot be
# defined at module-import time. It is built once on first use and cached here.
_TN_CLASS_CACHE = None


def _build_truncated_normal_class():
    """Build (once) the truncated-normal ``Distribution`` subclass.

    Deferred so torch is imported only when actually constructing a prior.
    """
    global _TN_CLASS_CACHE
    if _TN_CLASS_CACHE is not None:
        return _TN_CLASS_CACHE

    import torch
    from torch.distributions import Distribution, Normal, constraints

    class _TN(Distribution):
        # sbi's MultipleIndependent requires each component to advertise a
        # batchable interval support and an event_shape of (1,).
        arg_constraints = {}
        has_rsample = False

        def __init__(self, mean, std, low, high):
            self._mean = float(mean)
            self._std = float(std)
            self._low = float(low)
            self._high = float(high)
            self._m = torch.tensor(self._mean, dtype=torch.float32)
            self._s = torch.tensor(self._std, dtype=torch.float32)
            self._lo = torch.tensor(self._low, dtype=torch.float32)
            self._hi = torch.tensor(self._high, dtype=torch.float32)
            self._base = Normal(self._m, self._s)
            # CDF at the truncation points → normalization of the truncated pdf.
            self._Phi_lo = self._base.cdf(self._lo)
            self._Phi_hi = self._base.cdf(self._hi)
            self._Z = (self._Phi_hi - self._Phi_lo).clamp_min(1e-12)
            super().__init__(batch_shape=torch.Size([]),
                             event_shape=torch.Size([1]),
                             validate_args=False)

        def __reduce__(self):
            # Serialize via the MODULE-LEVEL reconstruction function so pickle
            # never needs to resolve this lazily-built class by name. Rebuilds
            # from the four scalars → robust across torch versions and
            # independent of cached tensor/Normal internals.
            return (_truncated_normal_from_scalars,
                    (self._mean, self._std, self._low, self._high))

        @constraints.dependent_property
        def support(self):
            return constraints.interval(self._lo, self._hi)

        def sample(self, sample_shape=torch.Size()):
            # Inverse-CDF (Smirnov) sampling of the truncated normal.
            shape = torch.Size(sample_shape) + torch.Size([1])
            u = torch.rand(shape)
            p = self._Phi_lo + u * (self._Phi_hi - self._Phi_lo)
            # standard-normal icdf, then rescale; clamp to guard fp edge cases.
            std_normal = Normal(torch.zeros(()), torch.ones(()))
            z = std_normal.icdf(p.clamp(1e-12, 1 - 1e-12))
            x = self._m + self._s * z
            return x.clamp(self._lo, self._hi)

        def log_prob(self, value):
            value = torch.as_tensor(value, dtype=torch.float32)
            lp = self._base.log_prob(value) - torch.log(self._Z)
            inside = (value >= self._lo) & (value <= self._hi)
            lp = torch.where(inside, lp,
                             torch.full_like(lp, float('-inf')))
            # collapse the event dim (1,) so MultipleIndependent sums correctly
            return lp.squeeze(-1)

    _TN_CLASS_CACHE = _TN
    return _TN


def _truncated_normal_from_scalars(mean, std, low, high):
    """Module-level reconstruction hook for pickling a truncated-normal prior.

    Referenced by ``_TN.__reduce__``; pickle stores THIS function's qualified
    name (``sbi_runner._truncated_normal_from_scalars``), which is always
    resolvable at import — unlike the lazily-built ``_TN`` class. On unpickle
    this rebuilds the class (torch is available in any artifact-loading context)
    and returns a fresh instance from the four constructor scalars.
    """
    return _build_truncated_normal_class()(mean, std, low, high)


def _TruncatedNormal1D(mean: float, std: float, low: float, high: float):
    """A 1-D truncated-normal torch Distribution matching scipy.truncnorm.

    v5 ice-thickness prior: N(mean, std) truncated to [low, high]. Built to be
    numerically identical to MCMCRunner's ``scipy.stats.truncnorm(a, b,
    loc=mean, scale=std)`` with ``a=(low−mean)/std, b=(high−mean)/std`` — the
    training thetas are drawn from that MCMC prior, so the SBI joint prior must
    represent the same density (event_shape (1,)) for the flow's leakage
    correction. Returned instance plugs into ``sbi.utils.MultipleIndependent``
    and pickles (via ``__reduce__``) so trained posteriors serialize.
    """
    return _truncated_normal_from_scalars(mean, std, low, high)


def _git_short_sha() -> Optional[str]:
    """Best-effort short git SHA for artifact provenance (None on failure)."""
    try:
        return subprocess.check_output(
            ['git', 'rev-parse', '--short', 'HEAD'],
            cwd=os.path.dirname(os.path.abspath(__file__)),
            stderr=subprocess.DEVNULL,
        ).decode().strip()
    except Exception:
        return None


class SBIRunner:
    """
    Single-round amortized NPE for interior-structure inference.

    Args:
        config: InferenceConfig with ``mode='sbi'``. ``sampler_settings``
            keys used here:

            - ``num_simulations`` (int, default 10000): training-set size
              requested from the prior (rows lost to rejection reduce the
              effective size, reported in rejection stats).
            - ``density_estimator`` (str, default 'maf'): flow type passed
              to sbi's NPE ('maf' default, 'nsf' optional).
            - ``n_posterior_samples`` (int, default 10000): posterior draws
              returned by ``run()``.
            - ``n_reeval`` (int, default 500): subset size for the heating
              recompute (same meaning as in MCMCRunner).
            - ``sbi_artifact_path`` (str, optional): explicit artifact
              location; otherwise ``sbi_artifacts/`` is scanned for a
              config-hash match and new artifacts are written there.
            - ``phase_stability`` (dict, optional): when
              ``{'enforce': 'no_ocean_Ih', ...}``, the training set is
              generated with the same no-ocean support guard the MCMC
              likelihood applies, so flow support matches MCMC support.

    Example:
        >>> config = InferenceConfig(mode='sbi', bodyname='Titan', ...)
        >>> runner = SBIRunner(config)
        >>> result = runner.run(progress_callback=my_callback)
    """

    def __init__(self, config):
        """Initialize SBI runner. Cheap: no structure cache, no torch/sbi."""
        from .inference_core import InferenceConfig

        if not isinstance(config, InferenceConfig):
            raise TypeError("config must be InferenceConfig instance")
        if config.mode != 'sbi':
            raise ValueError(f"SBIRunner requires config.mode='sbi', got '{config.mode}'")

        self.config = config
        self.param_names = list(config.param_space.keys())
        self.param_labels = self._make_labels(self.param_names)
        self.param_units = self._make_units(self.param_names)
        # x columns follow config.observables key order (same convention
        # as MCMCRunner.generate_sbi_dataset).
        self.obs_names = list(config.observables.keys())
        # All shipped artifacts use |Im k2| (see module docstring).
        self.imag_convention = 'abs'
        # Per-channel Im conventions; populated from obs_names below. Bind_
        # measurement-space channels are 'signed', k2/h2 Im follow
        # imag_convention. Recorded in the artifact by save_artifact.
        self.channel_conventions = self._channel_conventions()

        # Lazily constructed on first use (loads the structure cache).
        self._mcmc_runner = None
        # Populated by train() / load_artifact().
        self._posterior = None
        self._train_info: Dict[str, Any] = {}

    # ------------------------------------------------------------------
    # Metadata helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _make_labels(param_names):
        """LaTeX labels identical to MCMCRunner's (reuses its label map).

        ``MCMCRunner._make_label`` does not touch ``self``, so it is called
        unbound here to avoid constructing a runner (which would load the
        structure cache) just for labels.
        """
        from .mcmc_runner import MCMCRunner
        return [MCMCRunner._make_label(None, name) for name in param_names]

    @staticmethod
    def _make_units(param_names):
        """Physical units per parameter from the registry ('' if none)."""
        from .parameter_registry import PARAMETER_REGISTRY
        units = []
        for name in param_names:
            pdef = PARAMETER_REGISTRY.get(name)
            units.append(pdef.units if (pdef is not None and pdef.units) else '')
        return units

    def _channel_conventions(self) -> Dict[str, str]:
        """Per-observable Im-part convention: 'abs' (folded) or 'signed'.

        The GUI/pre-deploy contract historically assumed every artifact was
        globally ``imag_convention='abs'``. Europa Clipper v2 introduced
        signed-Im ``Bind_`` measurement-space channels alongside the
        abs-folded ``Im_k2``/``Im_h2``. This map makes the per-channel
        convention explicit so a consumer never abs-folds a Bind_ input.

        Bind_ channels are always 'signed'. The k2/h2 imaginary channels
        follow the runner's global ``imag_convention``. Purely-real or
        magnitude channels (Re_k2, CMR2, ...) are omitted (no Im ambiguity).
        """
        conv: Dict[str, str] = {}
        for name in self.obs_names:
            if name.startswith('Bind_'):
                conv[name] = 'signed'
            elif name in ('Im_k2', 'abs_Im_k2', 'Im_h2', 'abs_Im_h2'):
                conv[name] = self.imag_convention
        return conv

    def _param_bounds(self):
        """(low, high) lists in param_names order.

        Supports ``uniform`` and (v5) ``truncated_gaussian`` priors; both are
        bounded, so the box [low, high] is well-defined for each. The
        truncated-Gaussian shape itself is applied in :meth:`build_prior`
        (per-dim torch distribution) — here we only need the support box.
        """
        lows, highs = [], []
        for name in self.param_names:
            spec = self.config.param_space[name]
            prior_type = spec.get('prior_type', 'uniform')
            if prior_type not in ('uniform', 'truncated_gaussian'):
                raise NotImplementedError(
                    f"SBIRunner supports prior_type in {{'uniform', "
                    f"'truncated_gaussian'}} (each maps to an MCMC-matching "
                    f"torch distribution). Parameter '{name}' has "
                    f"prior_type='{prior_type}'. Extend build_prior() with a "
                    f"provably MCMC-matching torch distribution before using it."
                )
            bounds = spec.get('bounds')
            if bounds is None or len(bounds) != 2 or bounds[0] >= bounds[1]:
                raise ValueError(f"Parameter '{name}': missing or invalid bounds {bounds}")
            lows.append(float(bounds[0]))
            highs.append(float(bounds[1]))
        return lows, highs

    def _prior_spec(self) -> Dict[str, Dict[str, Any]]:
        """Serializable prior description stored in the artifact."""
        lows, highs = self._param_bounds()
        spec = {}
        for name, lo, hi in zip(self.param_names, lows, highs):
            pc = self.config.param_space[name]
            if pc.get('prior_type') == 'truncated_gaussian':
                spec[name] = {'prior_type': 'truncated_gaussian',
                              'mean': float(pc['mean']), 'std': float(pc['std']),
                              'bounds': [lo, hi]}
            else:
                spec[name] = {'prior_type': 'uniform', 'bounds': [lo, hi]}
        return spec

    def _get_mcmc_runner(self):
        """Construct (once) the MCMCRunner used for simulation and recompute.

        The MCMC config differs from the SBI config only in ``mode``; the
        parameter space, observables, structure cache, and likelihood are
        shared, which is what guarantees prior/likelihood consistency
        between the two inference modes.
        """
        if self._mcmc_runner is None:
            from .inference_core import InferenceConfig
            from .mcmc_runner import MCMCRunner
            cfg_dict = self.config.to_dict()
            cfg_dict['mode'] = 'mcmc'
            self._mcmc_runner = MCMCRunner(InferenceConfig.from_dict(cfg_dict))
        return self._mcmc_runner

    def _support_guard_active(self) -> bool:
        """True when the config enforces a support cut: the no-ocean
        phase-stability guard and/or one-sided induction bounds (ratified
        2026-07-12; e.g. Europa's |Ae_synodic| > 0.7)."""
        phase_stability = self.config.sampler_settings.get('phase_stability', {}) or {}
        if phase_stability.get('enforce') == 'no_ocean_Ih':
            return True
        return bool(getattr(self.config, 'induction_bounds', {}) or {})

    # ------------------------------------------------------------------
    # Prior
    # ------------------------------------------------------------------

    def build_prior(self):
        """Build a torch prior over the raw theta space from config.param_space.

        - All-``uniform`` param spaces → a single ``BoxUniform`` (unchanged;
          log10_* parameters are already in log space, no transform applied).
        - Any ``truncated_gaussian`` dim (v5 ice-thickness reparameterization)
          → a ``MultipleIndependent`` joint of per-dimension 1-D priors: a
          ``Uniform`` for uniform dims and a truncated-normal for the Gaussian
          dims, built to match MCMCRunner's ``scipy.stats.truncnorm(a, b,
          loc=mean, scale=std)`` EXACTLY (a=(low−mean)/std, b=(high−mean)/std).
          The training thetas are drawn from the MCMC prior, so the SBI prior
          MUST represent the identical density for the flow's leakage
          correction to be unbiased.

        Raises:
            NotImplementedError: for any unsupported prior_type (via
            :meth:`_param_bounds`).
        """
        torch, _ = _import_torch_sbi()
        from sbi.utils.torchutils import BoxUniform

        lows, highs = self._param_bounds()
        prior_types = [self.config.param_space[n].get('prior_type', 'uniform')
                       for n in self.param_names]

        if all(pt == 'uniform' for pt in prior_types):
            return BoxUniform(
                low=torch.as_tensor(lows, dtype=torch.float32),
                high=torch.as_tensor(highs, dtype=torch.float32),
            )

        # Mixed prior: one independent 1-D distribution per dimension.
        from sbi.utils import MultipleIndependent
        from torch.distributions import Uniform
        dists = []
        for name, lo, hi in zip(self.param_names, lows, highs):
            pc = self.config.param_space[name]
            if pc.get('prior_type') == 'truncated_gaussian':
                dists.append(_TruncatedNormal1D(
                    float(pc['mean']), float(pc['std']), lo, hi))
            else:
                dists.append(Uniform(
                    torch.tensor([lo], dtype=torch.float32),
                    torch.tensor([hi], dtype=torch.float32)))
        return MultipleIndependent(dists)

    # ------------------------------------------------------------------
    # Training set
    # ------------------------------------------------------------------

    def generate_training_set(
        self, n_simulations: int, seed: Optional[int] = None,
        obs_noise: bool = True, noise_seed: Optional[int] = None,
    ) -> Tuple[np.ndarray, np.ndarray, Dict[str, Any]]:
        """Generate the (theta, x) training set from the prior.

        Delegates to ``MCMCRunner.generate_sbi_dataset`` with the SBI
        scientific fixes enabled (plan doc, decision 2):

        - ``apply_support_guard=True`` only for configs that enforce the
          no-ocean guard (``sampler_settings['phase_stability']``), so the
          training-set support matches the MCMC posterior support;
        - ``imag_convention='abs'``: x stores |Im k2|;
        - ``drop_nonfinite=True``: TidalPy-failure NaN rows are rejected;
        - ``seed``: reproducible prior draws;
        - ``obs_noise=True`` (default): Gaussian observation noise with the
          config's per-observable sigma is added to x (data = |Im_model| +
          noise, no re-fold — the committed likelihood's generative model).
          Ratified 2026-07-09: REQUIRED for the trained flow to target the
          MCMC posterior; without it NPE learns the singular noiseless
          conditional and fails SBC/crosscheck. Only disable for diagnostics.

        Args:
            n_simulations: Number of prior draws requested. Rows lost to
                the support guard or non-finite outputs are excluded, so
                the returned arrays may have fewer rows.
            seed: Seed for the prior draws (None leaves the global RNG
                state untouched — pass a seed for reproducible datasets).
            obs_noise: Add observation noise to x (see above).
            noise_seed: Dedicated seed for the noise Generator (independent
                of the prior-draw seed).

        Returns:
            (theta, x, stats): theta (n_kept, D), x (n_kept, K) with
            columns in ``self.obs_names`` order, and the rejection-stats
            dict (n_requested, n_rejected_support, n_rejected_nonfinite,
            rejection_rate, imag_convention, seed).
        """
        runner = self._get_mcmc_runner()
        apply_guard = self._support_guard_active()
        theta, x = runner.generate_sbi_dataset(
            n_samples=n_simulations,
            apply_support_guard=apply_guard,
            imag_convention=self.imag_convention,
            drop_nonfinite=True,
            seed=seed,
            obs_noise=obs_noise,
            noise_seed=noise_seed,
        )
        stats = dict(getattr(runner, 'last_sbi_dataset_stats', {}) or {})
        stats.setdefault('n_requested', n_simulations)
        stats['apply_support_guard'] = apply_guard
        stats['n_kept'] = int(len(theta))
        return np.asarray(theta), np.asarray(x), stats

    # ------------------------------------------------------------------
    # Training
    # ------------------------------------------------------------------

    def train(
        self,
        theta: np.ndarray,
        x: np.ndarray,
        seed: Optional[int] = None,
        density_estimator: str = 'maf',
        show_progress_bars: bool = False,
        **train_kwargs,
    ):
        """Train a single-round NPE posterior estimator on (theta, x).

        Uses sbi's ``NPE`` trainer (alias of ``NPE_C``; verified in the
        installed sbi 0.26.1 ``sbi/inference/__init__.py``). Single-round
        training with prior samples uses the plain NLL loss, so the result
        is a fully amortized posterior q(theta | x). The default 'maf'
        density estimator z-scores theta and x internally
        (``posterior_nn`` default ``z_score='independent'``); those
        standardization layers are part of the saved estimator.

        Args:
            theta: (n, D) parameter draws from the prior (raw theta space).
            x: (n, K) simulated observables, columns in ``self.obs_names``
                order, |Im k2| convention. Must be finite.
            seed: torch.manual_seed value for reproducible training
                (None = do not reseed).
            density_estimator: 'maf' (default) or 'nsf'.
            show_progress_bars: Forwarded to the sbi trainer.
            **train_kwargs: Forwarded to ``NPE.train()`` (e.g.
                training_batch_size, stop_after_epochs).

        Returns:
            Trained ``DirectPosterior`` (also stored on ``self._posterior``).
        """
        torch, sbi_pkg = _import_torch_sbi()
        from sbi.inference import NPE

        theta = np.asarray(theta, dtype=np.float64)
        x = np.asarray(x, dtype=np.float64)
        if theta.ndim != 2 or x.ndim != 2 or len(theta) != len(x):
            raise ValueError(
                f"theta and x must be 2-D with equal row counts; "
                f"got theta {theta.shape}, x {x.shape}"
            )
        if theta.shape[1] != len(self.param_names):
            raise ValueError(
                f"theta has {theta.shape[1]} columns but config.param_space "
                f"has {len(self.param_names)} parameters"
            )
        if x.shape[1] != len(self.obs_names):
            raise ValueError(
                f"x has {x.shape[1]} columns but config.observables "
                f"has {len(self.obs_names)} entries"
            )
        if not np.all(np.isfinite(theta)) or not np.all(np.isfinite(x)):
            raise ValueError(
                "Non-finite values in training data. Generate the training "
                "set with drop_nonfinite=True (generate_training_set does)."
            )

        if seed is not None:
            torch.manual_seed(seed)

        prior = self.build_prior()
        theta_t = torch.as_tensor(theta, dtype=torch.float32)
        x_t = torch.as_tensor(x, dtype=torch.float32)

        log.info(
            f"Training NPE ({density_estimator}) on {len(theta)} simulations "
            f"({theta.shape[1]}D theta, {x.shape[1]}D x)..."
        )
        t0 = time.time()
        inference = NPE(
            prior=prior,
            density_estimator=density_estimator,
            show_progress_bars=show_progress_bars,
        )
        inference.append_simulations(theta_t, x_t).train(**train_kwargs)
        posterior = inference.build_posterior()
        elapsed = time.time() - t0
        log.info(f"NPE training complete in {elapsed/60:.1f} min")

        self._posterior = posterior
        # Informational normalization constants (z-scoring itself lives
        # inside the saved estimator; these are recorded for auditability).
        self._train_info.update({
            'density_estimator': density_estimator,
            'seed': seed,
            'n_train_effective': int(len(theta)),
            'theta_norm': {'mean': theta.mean(axis=0).tolist(),
                           'std': theta.std(axis=0).tolist()},
            'x_norm': {'mean': x.mean(axis=0).tolist(),
                       'std': x.std(axis=0).tolist()},
            'train_elapsed_s': elapsed,
        })
        return posterior

    # ------------------------------------------------------------------
    # Artifact I/O
    # ------------------------------------------------------------------

    def save_artifact(self, path) -> None:
        """Save the trained posterior + provenance to a self-describing .pt.

        Schema (version 1) — dict written with torch.save:
            schema_version, posterior (DirectPosterior, pickled),
            prior_spec, param_names, param_labels, param_units,
            param_bounds, obs_names, imag_convention, channel_conventions,
            theta_norm, x_norm,
            density_estimator, config_hash, bodyname, git_sha, seed,
            n_train_effective, rejection_stats, sbi_version, torch_version,
            created_utc.

        Args:
            path: Output .pt path (parent directories are created).
        """
        torch, sbi_pkg = _import_torch_sbi()

        if self._posterior is None:
            raise RuntimeError("No trained posterior to save. Call train() first.")

        lows, highs = self._param_bounds()
        artifact = {
            'schema_version': SBI_ARTIFACT_SCHEMA_VERSION,
            'posterior': self._posterior,
            'prior_spec': self._prior_spec(),
            'param_names': list(self.param_names),
            'param_labels': list(self.param_labels),
            'param_units': list(self.param_units),
            'param_bounds': [[lo, hi] for lo, hi in zip(lows, highs)],
            'obs_names': list(self.obs_names),
            'imag_convention': self.imag_convention,
            # Per-channel Im convention (additive, schema v1 compatible):
            # 'signed' for Bind_ measurement-space channels, the global
            # imag_convention for k2/h2 Im channels. Absent-key readers fall
            # back to the global imag_convention (old artifacts, no Bind_).
            'channel_conventions': self._channel_conventions(),
            'theta_norm': self._train_info.get('theta_norm'),
            'x_norm': self._train_info.get('x_norm'),
            'density_estimator': self._train_info.get('density_estimator'),
            'config_hash': self.config.generate_hash(),
            'bodyname': self.config.bodyname,
            'git_sha': _git_short_sha(),
            'seed': self._train_info.get('seed'),
            'n_train_effective': self._train_info.get('n_train_effective'),
            'rejection_stats': self._train_info.get('rejection_stats'),
            'sbi_version': sbi_pkg.__version__,
            'torch_version': torch.__version__,
            'created_utc': datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'),
        }
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        torch.save(artifact, path)
        log.info(f"SBI artifact saved: {path}")

    @staticmethod
    def _load_artifact_dict(path, validated_version_pairs=None) -> Dict[str, Any]:
        """torch.load an artifact dict with schema/version checks.

        Args:
            path: Artifact .pt path.
            validated_version_pairs: Optional iterable of
                ``(pkg_name, saved_version, installed_version)`` triples for
                which cross-version sampling has been gate-validated on this
                machine (see sbi_artifacts/INDEX.md). A matching mismatch is
                logged at INFO instead of raising the loud RuntimeWarning.
        """
        torch, sbi_pkg = _import_torch_sbi()
        validated = {tuple(t) for t in (validated_version_pairs or ())}

        def _norm(v):
            # Strip pip local build suffixes ('2.8.0+cpu' -> '2.8.0'): the
            # CPU wheel on cloud hosts is the same release as the validated
            # '2.8.0'; a genuinely different release still mismatches.
            return v.split('+')[0] if isinstance(v, str) else v

        path = Path(path)
        if not path.exists():
            raise FileNotFoundError(f"SBI artifact not found: {path}")
        # weights_only=False: the artifact pickles a full DirectPosterior
        # (schema v1). Only load artifacts from trusted sources.
        artifact = torch.load(path, map_location='cpu', weights_only=False)
        if not isinstance(artifact, dict) or 'schema_version' not in artifact:
            raise ValueError(f"Not a recognized SBI artifact (no schema_version): {path}")
        if artifact['schema_version'] != SBI_ARTIFACT_SCHEMA_VERSION:
            raise ValueError(
                f"SBI artifact schema_version {artifact['schema_version']} "
                f"is not supported (expected {SBI_ARTIFACT_SCHEMA_VERSION}): {path}"
            )

        # Loud version-mismatch warnings: pickled flow objects are not
        # guaranteed portable across sbi/torch versions.
        for pkg_name, installed, saved in (
            ('sbi', sbi_pkg.__version__, artifact.get('sbi_version')),
            ('torch', torch.__version__, artifact.get('torch_version')),
        ):
            if saved is not None and _norm(saved) != _norm(installed):
                if (pkg_name, _norm(saved), _norm(installed)) in validated:
                    log.info(
                        f"SBI artifact {path.name}: {pkg_name} {saved} -> "
                        f"{installed} mismatch is gate-validated on this "
                        f"machine (see sbi_artifacts/INDEX.md)."
                    )
                    continue
                msg = (
                    f"SBI artifact {path.name} was saved with {pkg_name} "
                    f"{saved} but {pkg_name} {installed} is installed. "
                    f"Pickled posterior objects may misbehave across versions "
                    f"— validate posterior draws before scientific use."
                )
                warnings.warn(msg, RuntimeWarning, stacklevel=3)
                log.warning(msg)
        return artifact

    @classmethod
    def load_artifact(cls, path, validated_version_pairs=None) -> 'SBIRunner':
        """Load a trained artifact for sampling only (no config, no cache).

        The returned object supports ``sample_posterior`` and exposes
        ``param_names`` / ``param_labels`` / ``param_units`` /
        ``obs_names`` / ``imag_convention`` / ``artifact_meta``, which is
        what the AmortizedInference GUI page consumes. It has no
        InferenceConfig and cannot ``run()`` or ``train()``.

        Args:
            path: Path to a .pt artifact written by save_artifact.

        Returns:
            SBIRunner instance in artifact-only mode.
        """
        artifact = cls._load_artifact_dict(
            path, validated_version_pairs=validated_version_pairs)

        obj = cls.__new__(cls)  # bypass __init__ (no config available)
        obj.config = None
        obj.param_names = list(artifact['param_names'])
        obj.param_labels = list(artifact['param_labels'])
        obj.param_units = list(artifact['param_units'])
        obj.obs_names = list(artifact['obs_names'])
        obj.imag_convention = artifact['imag_convention']
        # Per-channel Im conventions (empty for pre-v2 artifacts). Consumers
        # must NOT abs-fold a channel marked 'signed' (e.g. Bind_ family).
        obj.channel_conventions = dict(artifact.get('channel_conventions') or {})
        obj._mcmc_runner = None
        obj._posterior = artifact['posterior']
        obj._train_info = {
            'density_estimator': artifact.get('density_estimator'),
            'seed': artifact.get('seed'),
            'n_train_effective': artifact.get('n_train_effective'),
            'rejection_stats': artifact.get('rejection_stats'),
            'theta_norm': artifact.get('theta_norm'),
            'x_norm': artifact.get('x_norm'),
        }
        obj.artifact_meta = {
            k: v for k, v in artifact.items() if k != 'posterior'
        }
        log.info(
            f"SBI artifact loaded: {Path(path).name} "
            f"(body={artifact.get('bodyname')}, "
            f"n_train={artifact.get('n_train_effective')}, "
            f"sbi={artifact.get('sbi_version')})"
        )
        return obj

    # ------------------------------------------------------------------
    # Posterior sampling
    # ------------------------------------------------------------------

    def _x_obs_vector(self, x_obs: Dict[str, float]) -> np.ndarray:
        """Map an {observable_name: value} dict onto the trained x order.

        Accepts 'Im_k2' and 'abs_Im_k2' as aliases for the imaginary-k2
        channel; with imag_convention='abs' the value is |Im k2| (abs()
        is applied defensively so a signed input cannot silently condition
        the flow outside its training support).
        """
        vec = []
        for name in self.obs_names:
            if name in x_obs:
                val = float(x_obs[name])
            elif name in _IM_K2_ALIASES:
                alias = next((a for a in _IM_K2_ALIASES if a != name and a in x_obs), None)
                if alias is None:
                    raise KeyError(
                        f"x_obs missing observable '{name}' "
                        f"(aliases tried: {_IM_K2_ALIASES}); got keys {list(x_obs)}"
                    )
                val = float(x_obs[alias])
            else:
                raise KeyError(
                    f"x_obs missing observable '{name}'; got keys {list(x_obs)}"
                )
            # Fold EVERY channel trained as 'abs' (defensive: a signed
            # input must not condition the flow off its training manifold).
            # channel_conventions covers Im_k2 AND Im_h2 (and any future
            # abs channel); the alias check remains as fallback for
            # artifacts predating channel_conventions (2026-07-17), which
            # only had k2 aliases and a global imag_convention.
            # (Gap surfaced by Machine B 2026-07-18: Im_h2 was trained
            # folded but never folded here.)
            conv = getattr(self, 'channel_conventions', None) or {}
            _abs_fallback = _IM_K2_ALIASES + ('Im_h2', 'abs_Im_h2')
            if conv.get(name) == 'abs' or (
                    name not in conv and name in _abs_fallback
                    and self.imag_convention == 'abs'):
                val = abs(val)
            vec.append(val)
        return np.asarray(vec, dtype=np.float64)

    def sample_posterior(
        self,
        x_obs: Dict[str, float],
        n_samples: int = 10000,
        seed: Optional[int] = None,
        reject_outside_prior: bool = True,
    ) -> np.ndarray:
        """Draw posterior samples conditioned on observed data.

        Args:
            x_obs: Dict keyed by observable names (e.g.
                ``{'Re_k2': 0.608, 'abs_Im_k2': 0.135}``; 'Im_k2' is
                accepted as an alias, abs() is applied for the 'abs'
                convention). Values in the same units as the training x.
            n_samples: Number of posterior draws.
            seed: torch.manual_seed value for reproducible draws
                (None = do not reseed).
            reject_outside_prior: If True (default), sbi's DirectPosterior
                rejects proposals outside the prior box — the public
                contract: returned draws are valid posterior samples. Pass
                False ONLY for diagnostic sweeps at far-out-of-distribution
                x (e.g. validate_sbi's limits grid, where the NSF spline
                asserts under rejection at heavy-tailed x and the gate's own
                containment check measures the leakage honestly instead).

        Returns:
            (n_samples, D) numpy array in raw theta space,
            columns in ``param_names`` order.
        """
        torch, _ = _import_torch_sbi()

        if self._posterior is None:
            raise RuntimeError(
                "No trained posterior available. Call train()/run() or load_artifact() first."
            )

        # Conditioning vector is deterministic given x_obs — build it once, so
        # every resample attempt reuses the identical x (retries perturb only
        # the RNG, never the conditioning).
        x_vec = self._x_obs_vector(x_obs)
        x_t = torch.as_tensor(x_vec, dtype=torch.float32)

        # nflows spline-inversion resample guard (see _is_nflows_spline_assertion).
        # Scoped to the reject_outside_prior=True public/GUI contract path: the
        # diagnostic reject_outside_prior=False sweeps (validate_sbi limits grid)
        # deliberately drive x off-manifold and let the assert / containment
        # measure leakage honestly, so we must NOT silently resample there.
        guard_spline = bool(reject_outside_prior)
        base_seed = seed if seed is not None else 0
        for attempt in range(_MAX_SPLINE_RESAMPLE if guard_spline else 1):
            if seed is not None or attempt > 0:
                # Reseed on the caller's seed (reproducible) and, on retry, walk
                # to an independent RNG state for a genuinely fresh noise draw.
                torch.manual_seed(base_seed + attempt * _SPLINE_RESEED_STRIDE)
            try:
                samples = self._posterior.sample(
                    (int(n_samples),), x=x_t, show_progress_bars=False,
                    reject_outside_prior=reject_outside_prior,
                )
                break
            except AssertionError as exc:
                if not (guard_spline and _is_nflows_spline_assertion(exc)):
                    raise
                log.warning(
                    "nflows spline-inversion discriminant assert on posterior "
                    "sample (attempt %d/%d, n_samples=%d) — floating-point "
                    "roundoff on a bin edge; resampling with fresh RNG.",
                    attempt + 1, _MAX_SPLINE_RESAMPLE, int(n_samples),
                )
        else:
            # Exhausted every independent noise draw — this is not roundoff.
            raise RuntimeError(
                f"nflows spline inversion asserted on all "
                f"{_MAX_SPLINE_RESAMPLE} independent resample attempts at this "
                f"conditioning x — the flow is failing systematically here, not "
                f"from float roundoff. Do not silently accept these draws; "
                f"inspect the conditioning values (x_obs={x_obs})."
            )
        return samples.detach().cpu().numpy().astype(np.float64)

    # ------------------------------------------------------------------
    # Full pipeline
    # ------------------------------------------------------------------

    def _find_matching_artifact(self, config_hash: str) -> Optional[Path]:
        """Return the first artifact in sbi_artifacts/ whose config_hash matches."""
        explicit = self.config.sampler_settings.get('sbi_artifact_path')
        candidates = []
        if explicit:
            candidates.append(Path(explicit))
        if SBI_ARTIFACTS_DIR.is_dir():
            candidates.extend(sorted(SBI_ARTIFACTS_DIR.glob('*.pt')))
        for cand in candidates:
            if not cand.exists():
                continue
            try:
                artifact = self._load_artifact_dict(cand)
            except Exception as e:
                log.debug(f"Skipping unreadable SBI artifact {cand}: {e}")
                continue
            if artifact.get('config_hash') == config_hash:
                return cand
        return None

    def _default_artifact_path(self, config_hash: str) -> Path:
        """Default save location: sbi_artifacts/<body>_<hash>_posterior.pt."""
        explicit = self.config.sampler_settings.get('sbi_artifact_path')
        if explicit:
            return Path(explicit)
        return SBI_ARTIFACTS_DIR / (
            f"{self.config.bodyname.lower()}_{config_hash}_posterior.pt"
        )

    def run(self, progress_callback: Optional[Callable] = None):
        """Run the full SBI pipeline and return an InferenceResult.

        Steps:
          1. Reuse a trained artifact from ``sbi_artifacts/`` if one exists
             whose ``config_hash`` matches this config; otherwise generate
             ``sampler_settings['num_simulations']`` training simulations,
             train the flow, and save a new artifact.
          2. Condition on the central values of ``config.observables``
             (|Im k2| convention for the imaginary channel) and draw
             ``sampler_settings['n_posterior_samples']`` posterior samples.
          3. Recompute per-sample k2, CMR2, ocean/ice thicknesses, and a
             heating subset with the same MCMCRunner forward-model calls
             the MCMC path uses (no duplicated physics).
          4. Evaluate the Gaussian chi^2 log-likelihood for every sample
             with ``MCMCRunner``'s likelihood — this fills
             ``InferenceResult.log_likelihoods``. The flow's own log
             density (an amortized *posterior* estimate, NOT a likelihood)
             is stored in ``metadata['flow_log_prob']``.

        Args:
            progress_callback: Optional callable receiving a dict with
                keys iteration, n_total, n_samples (contract of
                ``inference_core.run_inference``).

        Returns:
            InferenceResult with unweighted posterior samples
            (``weights=None``).
        """
        from .inference_core import InferenceResult

        torch, sbi_pkg = _import_torch_sbi()

        settings = self.config.sampler_settings
        num_simulations = int(settings.get('num_simulations', 10000))
        n_posterior_samples = int(settings.get('n_posterior_samples', 10000))
        density_estimator = settings.get('density_estimator', 'maf')
        seed = int(self.config.random_state)
        config_hash = self.config.generate_hash()

        n_phases = 4  # dataset+train, sample, recompute, likelihood

        def _progress(phase: int, n_samples_now: int = 0):
            if progress_callback is not None:
                try:
                    progress_callback({
                        'iteration': phase,
                        'n_total': n_phases,
                        'n_samples': n_samples_now,
                    })
                except Exception:
                    pass

        t0 = time.time()
        log.info(f"Starting SBI (NPE) inference for {self.config.bodyname} "
                 f"({len(self.param_names)}D): {self.param_names}")
        log.info(f"Observables: {self.obs_names} (imag_convention="
                 f"'{self.imag_convention}')")

        # --- Step 1: artifact reuse or train --------------------------------
        rejection_stats: Optional[Dict[str, Any]] = None
        reused = False
        artifact_path = self._find_matching_artifact(config_hash)
        if artifact_path is not None:
            log.info(f"Reusing SBI artifact with matching config hash: {artifact_path}")
            artifact = self._load_artifact_dict(artifact_path)
            self._posterior = artifact['posterior']
            self._train_info = {
                'density_estimator': artifact.get('density_estimator'),
                'seed': artifact.get('seed'),
                'n_train_effective': artifact.get('n_train_effective'),
                'rejection_stats': artifact.get('rejection_stats'),
                'theta_norm': artifact.get('theta_norm'),
                'x_norm': artifact.get('x_norm'),
            }
            rejection_stats = artifact.get('rejection_stats')
            reused = True
        else:
            theta_train, x_train, rejection_stats = self.generate_training_set(
                num_simulations, seed=seed
            )
            if rejection_stats.get('rejection_rate', 0.0) > 0.20:
                # Plan-doc gate: stop and surface, do not train on a
                # significantly truncated support.
                raise RuntimeError(
                    f"SBI training-set rejection rate "
                    f"{rejection_stats['rejection_rate']:.1%} exceeds 20% "
                    f"({rejection_stats}). Inspect the prior/support guard "
                    f"before training — do not tune this check to pass."
                )
            self.train(
                theta_train, x_train, seed=seed,
                density_estimator=density_estimator,
            )
            self._train_info['rejection_stats'] = rejection_stats
            artifact_path = self._default_artifact_path(config_hash)
            self.save_artifact(artifact_path)
        _progress(1)

        # --- Steps 2-4: condition, recompute, package ------------------------
        x_obs = {name: spec[0] for name, spec in self.config.observables.items()}
        return self._condition_and_package(
            x_obs=x_obs,
            n_posterior_samples=n_posterior_samples,
            seed=seed,
            n_reeval=int(settings.get('n_reeval', 500)),
            artifact_path=artifact_path,
            reused=reused,
            rejection_stats=rejection_stats,
            config_hash=config_hash,
            t0=t0,
            progress_cb=_progress,
        )

    def _condition_and_package(
        self,
        x_obs: Dict[str, float],
        n_posterior_samples: int,
        seed: int,
        n_reeval: int,
        artifact_path,
        reused: bool,
        rejection_stats: Optional[Dict[str, Any]],
        config_hash: str,
        t0: float,
        progress_cb: Optional[Callable] = None,
        truncate_bounds: Optional[Dict[str, Tuple[float, float]]] = None,
        n_derived: Optional[int] = None,
    ):
        """Steps 2-4 of the SBI pipeline: condition the (already loaded or
        trained) flow on ``x_obs``, recompute derived quantities with the
        MCMC forward model, and package an InferenceResult.

        ``truncate_bounds`` ({param: (lo, hi)} strictly inside the trained
        prior box) applies EXACT uniform-prior truncation by rejection
        filtering of the drawn samples: for uniform priors, restricting the
        prior support and renormalizing is identical to conditioning the
        posterior on the sub-box, so filtering draws is exact (no
        reweighting needed). Oversamples in batches until
        ``n_posterior_samples`` survive (cap 10x); raises if the kept
        fraction falls below 1%.

        ``n_derived`` bounds the number of samples on which the forward-model
        derived quantities (k2/h2/CMR2/thicknesses/gravity) AND the true
        Gaussian log-likelihood are recomputed. It is the dominant cost of
        this method (two forward passes per sample). When set below
        ``n_samples`` a seeded subset (a SUPERSET of the heating subset, so
        heating rows always carry derived quantities) is recomputed and the
        remaining rows are NaN-padded; ``log_likelihoods`` is therefore a
        TRUE guard-aware chi^2 on the evaluated subset and NaN elsewhere
        (``get_best_fit`` uses ``nanargmax``). Full-density flow_log_prob
        stays over ALL samples. None => recompute all (the artifact/validation
        path; identical to the historical behavior).
        """
        from .inference_core import InferenceResult

        torch, sbi_pkg = _import_torch_sbi()

        def _progress(phase: int, n_samples_now: int = 0):
            if progress_cb is not None:
                try:
                    progress_cb(phase, n_samples_now)
                except TypeError:
                    pass

        # --- Step 2: condition on x_obs --------------------------------------
        kept_fraction = None
        if truncate_bounds:
            self._validate_truncation(truncate_bounds)
            idx_map = {name: self.param_names.index(name)
                       for name in truncate_bounds}
            # Rejection resampling with an ADAPTIVE budget: narrow multi-
            # parameter truncations legitimately sit at sub-percent
            # acceptance (fractions multiply across parameters), and flow
            # draws are cheap — so grow the batch toward the measured
            # acceptance instead of failing early. Hard failure only at
            # true starvation (the truncated region carries essentially no
            # posterior mass, where a rejection-based truncated posterior
            # would be statistical noise).
            kept = []
            n_kept = 0
            n_drawn = 0
            batch = int(n_posterior_samples)
            max_draws = max(300 * int(n_posterior_samples), 1_000_000)
            batch_seed = seed
            while n_kept < n_posterior_samples and n_drawn < max_draws:
                draw = self.sample_posterior(x_obs, n_samples=batch, seed=batch_seed)
                n_drawn += len(draw)
                mask = np.ones(len(draw), dtype=bool)
                for name, (lo, hi) in truncate_bounds.items():
                    col = draw[:, idx_map[name]]
                    mask &= (col >= lo) & (col <= hi)
                kept.append(draw[mask])
                n_kept += int(mask.sum())
                batch_seed = (batch_seed or 0) + 1
                # Scale the next batch to the observed acceptance (bounded).
                acc = max(n_kept / max(n_drawn, 1), 1e-6)
                need = n_posterior_samples - n_kept
                batch = int(np.clip(1.5 * need / acc, n_posterior_samples,
                                    500_000))
            samples = np.concatenate(kept, axis=0)
            kept_fraction = float(len(samples) / max(n_drawn, 1))
            if len(samples) < min(200, n_posterior_samples):
                raise RuntimeError(
                    f"Prior truncation keeps only {kept_fraction:.3%} of "
                    f"posterior draws ({len(samples)} kept from {n_drawn}; "
                    f"bounds {truncate_bounds}) — the truncated region "
                    f"carries essentially no posterior mass. Widen the "
                    f"truncation or use MCMC mode with tighter priors."
                )
            if kept_fraction < 0.01:
                log.warning(
                    f"Prior truncation acceptance is low "
                    f"({kept_fraction:.3%}; {len(samples)} samples kept from "
                    f"{n_drawn} draws). Results are valid but consider MCMC "
                    f"mode with tighter priors for efficiency.")
            samples = samples[:n_posterior_samples]
        else:
            samples = self.sample_posterior(
                x_obs, n_samples=n_posterior_samples, seed=seed
            )
        n_samples = len(samples)
        log.info(f"Drew {n_samples} posterior samples from the trained flow"
                 + (f" (truncated, kept_fraction={kept_fraction:.3f})"
                    if kept_fraction is not None else ""))
        _progress(2, n_samples)

        # Flow log density at the drawn samples (posterior density estimate,
        # NOT a likelihood — see module docstring). norm_posterior=False:
        # unnormalized w.r.t. prior-box leakage correction (a constant shift
        # per x_obs; rankings are unaffected).
        x_t = torch.as_tensor(self._x_obs_vector(x_obs), dtype=torch.float32)
        theta_t = torch.as_tensor(samples, dtype=torch.float32)
        with torch.no_grad():
            flow_log_prob = self._posterior.log_prob(
                theta_t, x=x_t, norm_posterior=False
            ).detach().cpu().numpy().astype(np.float64)

        # --- Steps 3+4: recompute derived quantities and likelihoods --------
        # Reuse MCMCRunner's forward-model calls and Gaussian likelihood so
        # SBI results are directly comparable to MCMC results (identical
        # physics, conventions, and guard behavior).
        runner = self._get_mcmc_runner()
        from .forward_models import (forward_model_k2_flexible,
                                      UnservableSampleError)
        from .mcmc_runner import _structure_R_body_km

        # Derived-quantity + likelihood recompute subset. This is the
        # dominant cost of amortized inference (two forward passes per
        # sample); ``n_derived`` bounds it for the interactive GUI. The
        # subset is a SUPERSET of the heating subset so every heating row
        # also carries k2/CMR2/etc., and rows outside it are NaN-padded to
        # preserve full length == n_samples (InferenceResult contract).
        n_reeval = min(int(n_reeval), n_samples)
        rng = np.random.RandomState(seed)
        idx_heat = rng.choice(n_samples, n_reeval, replace=False)
        idx_heat.sort()
        if n_derived is None or int(n_derived) >= n_samples:
            derived_indices = np.arange(n_samples)
        else:
            n_der = max(int(n_derived), n_reeval)
            n_der = min(n_der, n_samples)
            # Superset of the heating subset: keep idx_heat, fill the rest
            # from a seeded permutation of the remaining rows.
            heat_set = set(idx_heat.tolist())
            rng2 = np.random.RandomState(seed + 1)
            rest = np.array([i for i in rng2.permutation(n_samples)
                             if i not in heat_set], dtype=int)
            n_extra = max(n_der - len(idx_heat), 0)
            derived_indices = np.concatenate([idx_heat, rest[:n_extra]])
            derived_indices = np.unique(derived_indices)  # sorted
        n_der_eff = len(derived_indices)
        log.info(f"Recomputing k2/CMR2/thicknesses for {n_der_eff}/{n_samples} "
                 f"posterior samples"
                 + (" (full)" if n_der_eff == n_samples
                    else f" (n_derived={n_derived})") + " ...")

        gravity_active = runner._gravity_clairaut_active()
        # Full-length NaN-padded arrays; only derived_indices rows are filled.
        k2_results = np.full((n_samples, 2), np.nan)
        h2_results = np.full((n_samples, 2), np.nan)
        cmr2_results = np.full(n_samples, np.nan)
        D_ocean_results = np.full(n_samples, np.nan)
        D_iceIh_results = np.full(n_samples, np.nan)
        D_hsphere_results = np.full(n_samples, np.nan)
        D_iceHP_results = np.full(n_samples, np.nan)
        D_iceIII_results = np.full(n_samples, np.nan)
        D_iceV_results = np.full(n_samples, np.nan)
        D_iceVI_results = np.full(n_samples, np.nan)
        c20_results = np.full(n_samples, np.nan) if gravity_active else None
        c22_results = np.full(n_samples, np.nan) if gravity_active else None
        # Hydrostatic-reference C/MR² (RD inverse of the model C22); pairs with
        # cmr2_results (structure integral) for the non-hydrostaticity gap.
        cmr2_hydro_results = np.full(n_samples, np.nan) if gravity_active else None
        # True Gaussian chi^2 log-likelihood on the SAME subset, via the exact
        # MCMC likelihood (includes the no-ocean guard, which returns the
        # -1e30 sentinel for guard-violating draws). NaN outside the subset;
        # get_best_fit() uses nanargmax so it never selects a padded row.
        log_likelihoods = np.full(n_samples, np.nan)
        for count, i in enumerate(derived_indices):
            theta = samples[i]
            theta_dict = runner._expand_theta(theta)
            try:
                Re_k2, Im_k2, Re_h2, Im_h2, _ = forward_model_k2_flexible(
                    theta_dict, runner.structure_data,
                    return_heating=False, arrhenius_params=runner.arrhenius_params
                )
            except UnservableSampleError:
                # Posterior draw in an unbuilt 2D-cache corner (rare edge draw,
                # e.g. a D_iceIh value that inverts to an out-of-grid Tb): report
                # NaN k2/h2 rather than crash the recompute loop. Mirrors the
                # MCMC recompute guard (mcmc_runner.py) and the likelihood REJECT.
                # Surfaced when the induction channel is dropped (noinduction
                # artifact) — induction otherwise pins Tb into built regions.
                Re_k2 = Im_k2 = Re_h2 = Im_h2 = np.nan
            k2_results[i] = (Re_k2, Im_k2)
            h2_results[i] = (Re_h2, Im_h2)
            # CMR2 must use the same dispatch as the likelihood/reporting fix
            # (2026-07): _compute_model_cmr2 is core-sensitive for v2 configs
            # (sampled core + mass-conservation rho_sil, e.g. Europa 7D) and
            # falls back to the cache scalar for core-blind v1 configs. The
            # previous _get_cache_scalar call here ignored the sampled core,
            # displaying a CMR2 distribution systematically offset from the
            # Gaussian the flow was conditioned on (user-reported 2026-07-13:
            # Europa MoI 'far left of the Gaussian' in the GUI).
            cmr2_results[i] = runner._compute_model_cmr2(theta_dict)
            D_ocean_results[i] = runner._get_cache_scalar(theta_dict, 'D_ocean_km')
            D_iceIh_results[i] = runner._get_cache_scalar(theta_dict, 'D_iceIh_km')
            D_hsphere_results[i] = runner._get_cache_scalar(theta_dict, 'D_hsphere_km')
            _phases = runner._ice_phase_thicknesses_km(theta_dict)
            D_iceIII_results[i] = _phases['III']
            D_iceV_results[i] = _phases['V']
            D_iceVI_results[i] = _phases['VI']
            D_iceHP_results[i] = _phases['III'] + _phases['V'] + _phases['VI']
            if gravity_active:
                pair = runner._derive_gravity_pair(theta_dict)
                c20_results[i] = pair[0] if pair is not None else np.nan
                c22_results[i] = pair[1] if pair is not None else np.nan
                # _derive_gravity_pair stashes the hydrostatic-reference C/MR²
                # (same geometry as the pair) on _last_cmr2_hydro; None if the
                # pair rejected or C22 was RD-unphysical.
                _h = getattr(runner, '_last_cmr2_hydro', None)
                cmr2_hydro_results[i] = _h if _h is not None else np.nan
            log_likelihoods[i] = float(runner.log_likelihood_fn(theta))
            if (count + 1) % 100 == 0:
                log.info(f"  {count+1}/{n_der_eff} samples recomputed")
        _progress(3, n_samples)

        # Heating on the seeded subset (same pattern/settings as
        # MCMCRunner.run); idx_heat ⊆ derived_indices by construction.
        log.info(f"Recomputing heating for {n_reeval} posterior samples...")
        heating_results = []
        for si in idx_heat:
            theta_dict = runner._expand_theta(samples[si])
            try:
                _, _, _, _, perPhase_W = forward_model_k2_flexible(
                    theta_dict, runner.structure_data,
                    return_heating=True, arrhenius_params=runner.arrhenius_params
                )
            except UnservableSampleError:
                perPhase_W = None
            heating_results.append(perPhase_W if perPhase_W is not None else {})
        _progress(4, n_samples)

        elapsed = time.time() - t0
        log.info(f"SBI inference complete: {n_samples} samples in {elapsed/60:.1f} min")

        convergence_metrics = {
            'n_samples': int(n_samples),
            'sampler': 'sbi_npe_single_round',
            # No MCMC-style diagnostics apply; SBC/cross-check validation is
            # the Phase-E gate (plan doc, decision 4).
            'ess': float(n_samples),
            'acceptance_rate': None,
            'r_hat': None,
        }

        result = InferenceResult(
            config=self.config,
            samples=samples,
            log_likelihoods=log_likelihoods,
            param_names=self.param_names,
            param_labels=self.param_labels,
            k2_results=k2_results,
            h2_results=h2_results,
            cmr2_results=cmr2_results,
            D_ocean_results=D_ocean_results,
            D_iceIh_results=D_iceIh_results,
            D_hsphere_results=D_hsphere_results,
            D_iceHP_results=D_iceHP_results,
            D_icePhase_results={'III': D_iceIII_results,
                                'V': D_iceV_results,
                                'VI': D_iceVI_results},
            c20_results=c20_results,
            c22_results=c22_results,
            cmr2_hydro_results=cmr2_hydro_results,
            heating_results=heating_results,
            convergence_metrics=convergence_metrics,
            metadata={
                'sampler': 'sbi',
                'density_estimator': self._train_info.get('density_estimator'),
                'elapsed_time_s': elapsed,
                'heating_indices': idx_heat,
                # Rows on which derived quantities + true log-likelihood were
                # recomputed (a superset of heating_indices). Equals all
                # samples when n_derived is None. Other rows are NaN-padded.
                'derived_indices': derived_indices,
                'artifact_path': str(artifact_path),
                'artifact_reused': reused,
                'config_hash': config_hash,
                'git_sha': _git_short_sha(),
                'seed': seed,
                'train_seed': self._train_info.get('seed'),
                'n_train_effective': self._train_info.get('n_train_effective'),
                'rejection_stats': rejection_stats,
                'x_obs': x_obs,
                'imag_convention': self.imag_convention,
                # Body radius (constant across the Tb grid) so the GUI can
                # derive mantle thickness = R_body - D_hsphere - R_core.
                'R_body_km': _structure_R_body_km(runner.structure_data),
                # Posterior induction response — identical schema to the
                # MCMC path (runner symmetry): complex Ae per excitation
                # label per sample + excitation moments.
                'induction_Ae': runner._collect_posterior_Ae(samples),
                'Be_nT': runner._be_excitation_metadata(),
                # Amortized posterior density at each sample (NOT a likelihood).
                'flow_log_prob': flow_log_prob,
                'sbi_version': sbi_pkg.__version__,
                'torch_version': torch.__version__,
                'truncate_bounds': ({k: [float(lo), float(hi)]
                                     for k, (lo, hi) in truncate_bounds.items()}
                                    if truncate_bounds else None),
                'kept_fraction': kept_fraction,
                'training_obs_noise': (rejection_stats or {}).get('obs_noise'),
            },
            weights=None,
        )
        return result

    def _validate_truncation(
        self, truncate_bounds: Dict[str, Tuple[float, float]]
    ) -> None:
        """Truncation sub-box must name known params and lie inside the
        trained prior box (widening cannot be done post hoc)."""
        lows, highs = self._param_bounds()
        box = dict(zip(self.param_names, zip(lows, highs)))
        for name, (lo, hi) in truncate_bounds.items():
            if name not in box:
                raise ValueError(f"truncate_bounds: unknown parameter '{name}'")
            blo, bhi = box[name]
            if not (blo <= lo < hi <= bhi):
                raise ValueError(
                    f"truncate_bounds for '{name}' = ({lo}, {hi}) must lie "
                    f"strictly inside the trained prior box ({blo}, {bhi}); "
                    f"widening requires retraining."
                )

    def infer_from_artifact(
        self,
        artifact_path,
        x_obs: Optional[Dict[str, float]] = None,
        n_posterior_samples: int = 10000,
        seed: int = 42,
        n_reeval: int = 500,
        truncate_bounds: Optional[Dict[str, Tuple[float, float]]] = None,
        progress_callback: Optional[Callable] = None,
        validated_version_pairs=None,
        n_derived: Optional[int] = None,
    ):
        """Amortized inference from a pretrained artifact — NEVER trains.

        Loads the artifact into this runner, validates compatibility with
        ``self.config`` (parameter set, observable set, |Im k2| convention,
        and the trained prior box — priors and observation noise are frozen
        at training time; only observable VALUES are free), conditions the
        flow, and packages the same InferenceResult the MCMC path produces
        (forward-model recompute of k2/CMR2/thicknesses/heating + Gaussian
        log-likelihoods).

        Args:
            artifact_path: Trained .pt artifact.
            x_obs: Observable values to condition on (defaults to
                ``config.observables`` central values). Aliased 'Im_k2' /
                'abs_Im_k2' accepted.
            n_posterior_samples / seed / n_reeval: as in run().
            n_derived: Optional cap on forward-model derived-quantity +
                true-likelihood recompute (the dominant cost). See
                ``_condition_and_package``. None => recompute all.
            truncate_bounds: Optional exact uniform-prior truncation, a
                {param: (lo, hi)} sub-box of the trained prior
                (see ``_condition_and_package``).
            progress_callback: Same contract as run().
            validated_version_pairs: See ``_load_artifact_dict``.

        Returns:
            InferenceResult (metadata['mode'] = 'amortized').
        """
        artifact = self._load_artifact_dict(
            artifact_path, validated_version_pairs=validated_version_pairs)

        # Compatibility: the artifact must describe the same inference
        # problem the config poses. Values of observables are free; names,
        # parameter set, convention, and prior box are not.
        art_params = list(artifact['param_names'])
        if art_params != self.param_names:
            raise ValueError(
                f"Artifact parameters {art_params} != config parameters "
                f"{self.param_names}"
            )
        art_obs = list(artifact['obs_names'])
        if art_obs != self.obs_names:
            raise ValueError(
                f"Artifact observables {art_obs} != config observables "
                f"{self.obs_names}"
            )
        if artifact.get('imag_convention') != self.imag_convention:
            raise ValueError(
                f"Artifact imag_convention '{artifact.get('imag_convention')}'"
                f" != '{self.imag_convention}'"
            )
        art_bounds = [tuple(map(float, b)) for b in artifact['param_bounds']]
        lows, highs = self._param_bounds()
        cfg_bounds = list(zip(lows, highs))
        if not np.allclose(np.asarray(art_bounds), np.asarray(cfg_bounds)):
            raise ValueError(
                f"Artifact prior box {art_bounds} != config prior box "
                f"{cfg_bounds}. Priors are frozen at training time; build "
                f"the config from the artifact's metadata (narrow the "
                f"posterior with truncate_bounds instead)."
            )

        self._posterior = artifact['posterior']
        self._train_info = {
            'density_estimator': artifact.get('density_estimator'),
            'seed': artifact.get('seed'),
            'n_train_effective': artifact.get('n_train_effective'),
            'rejection_stats': artifact.get('rejection_stats'),
            'theta_norm': artifact.get('theta_norm'),
            'x_norm': artifact.get('x_norm'),
        }

        if x_obs is None:
            x_obs = {name: spec[0]
                     for name, spec in self.config.observables.items()}

        def _progress(phase: int, n_samples_now: int = 0):
            if progress_callback is not None:
                try:
                    progress_callback({
                        'iteration': phase, 'n_total': 4,
                        'n_samples': n_samples_now,
                    })
                except Exception:
                    pass

        result = self._condition_and_package(
            x_obs={k: float(v) for k, v in x_obs.items()},
            n_posterior_samples=int(n_posterior_samples),
            seed=int(seed),
            n_reeval=int(n_reeval),
            artifact_path=artifact_path,
            reused=True,
            rejection_stats=artifact.get('rejection_stats'),
            config_hash=artifact.get('config_hash', ''),
            t0=time.time(),
            progress_cb=_progress,
            truncate_bounds=truncate_bounds,
            n_derived=n_derived,
        )
        result.metadata['mode'] = 'amortized'
        result.metadata['artifact_created_utc'] = artifact.get('created_utc')
        return result
