"""v5 baseline reference MCMC (pocoMC) — reproducible driver.

Runs the full 21-observable baseline reference posterior with pocoMC against the
PIVOTED v5 config (open-interpretation redesign 2026-07-21: D_iceIh uniform[5,80]
+ per-frequency degree-based induction support). This is the ratification-blocking
reference the baseline SBI flow is crosschecked against (validate_sbi crosscheck).

Why this driver exists
----------------------
The pre-pivot reference pickle (2026-07-20) was produced ad-hoc, with no committed
command — a reproducibility gap. This script captures the exact, re-runnable
procedure so the reference can be regenerated by anyone from the config alone, and
so the same recipe transfers to other bodies (swap the config path).

Determinism
-----------
- MCMC seed is taken from the config's ``sampler_settings.random_state`` if present,
  else the ``--seed`` CLI arg (default 51, the v5 train seed) — recorded in the
  result metadata and the sidecar manifest.
- The forward model reads the pinned v5 (Tb x w) structure cache + Ae sidecar named
  in the config; their sha256 are recorded so a reader can confirm the same cache.

Outputs
-------
- Reference pickle -> the config's Test/ location (committed; permission granted
  2026-07-18). Written to /tmp first, then copied to Dropbox (per repo memory).
- A JSONL progress log + a run manifest (seed, config_hash, cache sha256, ESS,
  log_Z, elapsed, git_sha, sample count) alongside the pickle.

Run
---
  mamba run -n PPcl env PYTHONPATH=. NUMBA_CACHE_DIR=/tmp/pp_numba_cache \
    KMP_DUPLICATE_LIB_OK=TRUE python plans/scripts/v6_reference_mcmc.py
"""
import argparse
import hashlib
import json
import os
import shutil
import subprocess
import time
from pathlib import Path

import numpy as np

from PlanetProfile.Inference.inference_core import InferenceConfig
from PlanetProfile.Inference.mcmc_runner import MCMCRunner

ROOT = Path(__file__).resolve().parents[2]
CFG = ROOT / "PlanetProfile/Inference/configs/europa_clipper_v6_freegrav_11D.json"
# Destination for the committed reference pickle (config's Test/ tree).
REF_DST = (ROOT / "PlanetProfile/Test/mcmc_results/Europa/Test53_seawater_v6/"
           "europa_clipper_v6_reference_result.pkl")
TMP_DIR = Path("/tmp/v6_build/reference")
DEFAULT_SEED = 61


def _sha256(path):
    if not path or not os.path.exists(path):
        return None
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _git_sha():
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=ROOT).decode().strip()
    except Exception:
        return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=str(CFG))
    ap.add_argument("--seed", type=int, default=DEFAULT_SEED)
    ap.add_argument("--dst", default=str(REF_DST),
                    help="final (committed) pickle path; written via /tmp first")
    args = ap.parse_args()

    TMP_DIR.mkdir(parents=True, exist_ok=True)
    cfg = InferenceConfig.from_json(args.config)

    # Seed precedence: config sampler_settings.random_state, else CLI.
    seed = int((cfg.sampler_settings or {}).get("random_state", args.seed))

    print(f"[ref] config={args.config}")
    print(f"[ref] observables ({len(cfg.observables)}): {list(cfg.observables)}")
    print(f"[ref] param_space: {list(cfg.param_space.keys())}")
    print(f"[ref] n_effective={cfg.sampler_settings.get('n_effective')}  seed={seed}")

    runner = MCMCRunner(cfg)
    # Pin the sampler RNG deterministically.
    runner.random_state = seed

    cache_path = cfg.structure_cache_path
    sidecar_path = str(cache_path) + ".ae_sidecar.pkl"
    cache_sha = _sha256(cache_path)
    sidecar_sha = _sha256(sidecar_path)
    print(f"[ref] structure cache sha256 = {cache_sha}")
    print(f"[ref] Ae sidecar     sha256 = {sidecar_sha}")

    jsonl = TMP_DIR / "v6_reference_progress.jsonl"
    t0 = time.time()
    print(f"[ref] starting pocoMC ... (progress -> {jsonl})")
    result = runner.run(progress_jsonl_path=str(jsonl))
    dt = time.time() - t0

    samples = np.asarray(result.samples)
    md = getattr(result, "metadata", {}) or {}
    n_samples = int(samples.shape[0])
    log_Z = md.get("log_Z")
    print(f"[ref] done in {dt/60:.1f} min: samples={samples.shape} "
          f"log_Z={log_Z}")

    # Write to /tmp first, then copy to Dropbox (repo memory: avoid sync races).
    tmp_pkl = TMP_DIR / "europa_clipper_v6_reference_result.pkl"
    result.save(str(tmp_pkl))

    manifest = {
        "kind": "v6_baseline_reference_mcmc",
        "config": os.path.relpath(args.config, ROOT),
        "config_hash": cfg.generate_hash(),
        "seed": seed,
        "n_effective": cfg.sampler_settings.get("n_effective"),
        "n_samples": n_samples,
        "log_Z": log_Z,
        "log_Z_err": md.get("log_Z_err"),
        "elapsed_time_s": dt,
        "obs_names": list(cfg.observables),
        "param_names": list(result.param_names),
        "structure_cache_path": str(cache_path),
        "structure_cache_sha256": cache_sha,
        "ae_sidecar_sha256": sidecar_sha,
        "git_sha": _git_sha(),
        "prior_note": ("PIVOTED open-interpretation config: D_iceIh uniform[5,80] "
                       "km, per-frequency degree-based induction support "
                       "(synodic/synodic-2nd |Ae|>0.70 phase<30deg; "
                       "orbital |Ae|>0.30 phase<70deg)."),
    }
    tmp_manifest = TMP_DIR / "v6_reference_manifest.json"
    with open(tmp_manifest, "w") as f:
        json.dump(manifest, f, indent=2, default=str)

    # Copy pickle + manifest + progress into the committed Test/ location.
    dst = Path(args.dst)
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(tmp_pkl, dst)
    shutil.copy2(tmp_manifest, dst.parent / "v6_reference_manifest.json")
    shutil.copy2(jsonl, dst.parent / "v6_reference_progress.jsonl")
    print(f"[ref] reference pickle -> {dst}")
    print(f"[ref] manifest         -> {dst.parent / 'v6_reference_manifest.json'}")
    print(f"[ref] progress log     -> {dst.parent / 'v6_reference_progress.jsonl'}")


if __name__ == "__main__":
    main()
